import { createFileRoute } from "@tanstack/react-router";
import { Layout } from "@/components/Layout";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — CrediFi" },
      {
        name: "description",
        content:
          "Terms and conditions for use of the CrediFi experimental lending platform.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <Layout>
      <article className="max-w-2xl mx-auto px-4 sm:px-6 py-16 sm:py-20 leading-[1.75] text-[15px] text-foreground/90">
        <h1 className="font-display text-3xl sm:text-4xl font-semibold tracking-tight text-foreground">
          Terms &amp; Conditions
        </h1>
        <p className="mt-3 text-sm text-muted-foreground">
          Last updated: June 22, 2026
        </p>

        <p className="mt-10 font-semibold uppercase tracking-wide text-sm text-foreground">
          Important — Please read carefully before using CrediFi
        </p>

        <Section n="1" title="Experimental Software Notice">
          CrediFi is experimental software built for the HSK Chain "On-Chain
          Horizon" Hackathon. It is provided for demonstration, testing, and
          evaluation purposes. It has NOT been professionally audited. Use at
          your own risk.
        </Section>

        <Section n="2" title="No Financial Advice">
          Nothing on this platform constitutes financial, legal, investment, or
          tax advice. Credit scores, tiers, and rates generated by CrediFi are
          algorithmic outputs based on on-chain data and do not reflect, and
          should not be interpreted as, a real-world creditworthiness
          assessment by any licensed financial institution.
        </Section>

        <Section n="3" title="Risks of Use">
          <p>
            By using CrediFi, you acknowledge and accept the following risks,
            without limitation:
          </p>
          <ul className="mt-3 space-y-2 list-disc pl-5 marker:text-muted-foreground">
            <li>
              <strong className="font-semibold">Smart contract risk:</strong>{" "}
              bugs, vulnerabilities, or exploits in the underlying code may
              result in partial or total loss of deposited or collateralized
              funds.
            </li>
            <li>
              <strong className="font-semibold">Oracle risk:</strong> the credit
              scoring mechanism relies on an off-chain computation and signing
              process; errors, delays, or manipulation of this process may
              affect loan terms.
            </li>
            <li>
              <strong className="font-semibold">Liquidation risk:</strong>{" "}
              borrowed positions may be liquidated if collateral value falls
              below required thresholds, which may result in loss of
              collateral.
            </li>
            <li>
              <strong className="font-semibold">Market and token risk:</strong>{" "}
              the value of HSK and any other tokens used on this platform may
              be highly volatile.
            </li>
            <li>
              <strong className="font-semibold">
                No insurance or guarantee:
              </strong>{" "}
              deposited funds are not insured or guaranteed by CrediFi, HashKey
              Group, or any other party.
            </li>
          </ul>
        </Section>

        <Section n="4" title="No Custody, No Warranty">
          CrediFi does not custody user funds outside of the on-chain smart
          contracts, which operate autonomously according to their deployed
          code. CrediFi is provided "AS IS" and "AS AVAILABLE," without
          warranties of any kind, express or implied, including but not limited
          to warranties of merchantability, fitness for a particular purpose,
          or non-infringement.
        </Section>

        <Section n="5" title="Eligibility">
          You must be of legal age in your jurisdiction and legally permitted
          to use blockchain-based financial software under applicable local
          law. You are solely responsible for determining whether your use of
          CrediFi complies with the laws and regulations applicable to you.
        </Section>

        <Section n="6" title="Wallet Responsibility">
          You are solely responsible for the security of your own wallet,
          private keys, and seed phrases. CrediFi will never ask for your
          private keys or seed phrase. Loss of access to your wallet may result
          in permanent loss of access to your funds.
        </Section>

        <Section n="7" title="Data and Privacy">
          CrediFi computes credit scores using publicly available on-chain
          transaction history on HSK Chain. No personal identifying
          information, off-chain financial data, or private data is collected
          or required to use the platform in its current form.
        </Section>

        <Section n="8" title="No Liability">
          To the maximum extent permitted by applicable law, CrediFi, its
          developers, and contributors shall not be liable for any direct,
          indirect, incidental, special, or consequential damages arising from
          your use of, or inability to use, the platform.
        </Section>

        <Section n="9" title="Changes to These Terms">
          These Terms may be updated at any time without prior notice.
          Continued use of CrediFi after changes are posted constitutes
          acceptance of the updated Terms.
        </Section>

        <Section n="10" title="Contact">
          This is a hackathon project. For questions, please reach out via the
          project's GitHub repository.
        </Section>

        <hr className="my-12 border-border/60" />

        <p className="text-xs text-muted-foreground leading-relaxed">
          This document is a general disclaimer drafted for a hackathon project
          and does not constitute formal legal advice. It should be reviewed by
          a qualified legal professional before any production or mainnet use
          beyond demonstration purposes.
        </p>
      </article>
    </Layout>
  );
}

function Section({
  n,
  title,
  children,
}: {
  n: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-xl font-semibold text-foreground tracking-tight">
        <span className="text-muted-foreground font-mono text-base mr-3">
          {n}.
        </span>
        {title}
      </h2>
      <div className="mt-3 text-foreground/85">{children}</div>
    </section>
  );
}
